name: Build container
env:
  VERSION: 0.0.2
  IMAGE_NAME: "melotts"
  REGISTRY: image-registry.bwgdi.com
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BWGDI_NAME }}
          password: ${{ secrets.BWGDI_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/library/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
